Optimize ColGroup.resize()
Change colgroup.resize() implementation to use ndarray.resize() instead on
numpy.resize().  That may help with an issue that Doug Finkbeiner reported
with big result sets with numpy 1.6:

==========
Traceback (most recent call last):
  File "/n/fink1/lsd/stable/bin/lsd-query", line 105, in <module>
    rows = q.fetch(bounds, progress_callback=progress_callback, testbounds=testbounds, include_cached=include_cached)
  File "/n/fink1/lsd/stable/lib/python/lsd/join_ops.py", line 1596, in fetch
    blocks=True
  File "/n/fink1/lsd/stable/lib/python/lsd/colgroup.py", line 613, in fromiter
    buf.resize(newsize)
  File "/n/fink1/lsd/stable/lib/python/lsd/colgroup.py", line 412, in resize
    self.column_data[pos] = np.resize(col, (size,) + col.shape[1:])
  File "/n/sw/hpc-001/numpy-1.6.0/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 864, in resize
    a = concatenate( (a,)*n_copies)
ValueError: negative dimensions are not allowed
Traceback (most recent call last):
  File "/n/sw/hpc-001/python-2.7.1/lib/python2.7/multiprocessing/queues.py", line 242, in _feed
[dfink@fink1 decam-ucal-qy]$
==========

I suspect this is due to an integer overflow in the implementation of
np.concatenate(), but I don't know for sure...